version: '3'

services:
    
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:8080"
  #     - "443:443"
  #     # - "5000"
  #   volumes:
  #     - .:/code
  #     - ./nginx:/etc/nginx/conf.d
  #   depends_on:
  #     - backend
      
  db:
    image: postgres:10.1-alpine
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data
        
       
  backend:
    build: .
    # restart: unless-stopped
    volumes:
      - .:/code
    depends_on:
      - db
    command: bash -c "cd svinbin && 
                      python manage.py makemigrations --no-input &&
                      python manage.py migrate &&
                      python manage.py test workshopthree.tests.test_views"
                      # python manage.py test workshopfour.tests.test_views"
                      # python manage.py test transactions.tests.test_models"
                      # python manage.py test sows.tests.test_managers"

    # command: bash -c "cd svinbin && 
    #                   python manage.py makemigrations --no-input &&
    #                   python manage.py migrate &&
    #                   python manage.py runserver 0.0.0.0:8000"
   
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  # viber:
  #   build: ./viberapi
  #   volumes:
  #     - .:/code

  #   command: bash -c "cd viberapi && python viber-flask.py"
  #   ports:
  #     - "5000"
         
# volumes:
  # postgres_data:
