version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
      - image: postgres:10.1-alpine
    resource_class: medium
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd svinbin
            python manage.py migrate
            python manage.py makemigrations --no-input
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app